#!/usr/bin/env bash

# UI

bspc config border_width 1 # Borders and gaps
bspc config window_gap 4
bspc config split_ratio 0.50

bspc config normal_border_color "#2E3440" # Nord colourscheme
bspc config active_border_color "#ECEFF4"
bspc config focused_border_color "#88C0D0"
bspc config presel_feedback_color "#EBCB8B"

# Monitors

bspc monitor -d '1' '2' '3' '4' '5' '6'
bspc monitor HDMI-A-0 '7'

# UX

bspc config borderless_monocle true # Make monocle mode useful
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle true

# bspc config focus_follows_pointer true # Choose after preference
bspc config click_to_focus any

bspc rule -a Code desktop='1' follow=on focus=on

bspc rule -a krita desktop='1' follow=on focus=on

bspc rule -a kdenlive desktop='1' follow=on focus=on

bspc rule -a Firefox desktop='2'

bspc rule -a Chromium desktop='3'

bspc rule -a Bitwarden desktop='3'

bspc rule -a Geary desktop='4'

bspc rule -a discord desktop='5'

bspc rule -a Zathura state=tiled
